import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  platformWin: [{ type: 'autogenerated', dirName: 'platform/win' }],
  platformMac: [{ type: 'autogenerated', dirName: 'platform/mac' }],
  platformLinux: [{ type: 'autogenerated', dirName: 'platform/linux' }],
  platformAndroiod: [{ type: 'autogenerated', dirName: 'platform/android' }],
  platformNode: [{ type: 'autogenerated', dirName: 'platform/node' }],

  community: [{ type: 'autogenerated', dirName: 'community' }],
}

export = sidebars
