import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig[string] = [
  { type: 'autogenerated', dirName: 'platform/win' },
  { type: 'autogenerated', dirName: 'platform/mac' },
  { type: 'autogenerated', dirName: 'platform/linux' },
  { type: 'autogenerated', dirName: 'platform/android' },
  { type: 'autogenerated', dirName: 'platform/node' },
]

export default sidebars
